### ISSUE TITLE
Basemap is not loading

### ISSUE THREAD

**Issue by hhkaos** [BrianBunker/geometry-inspector#4]
First of all, thanks Brian for this tool! I have been using it quite often :).

I just noticed that the basemap is not loading. I have no time right now to check, but at least I wanted to open the issue. I'll be traveling to San Diego next week, by any chance... you're not going to be around, are you?

**Comment by BrianBunker** [comment]
Thanks for the kudos, glad it's been helpful.

Looks like arcgisonline restricted their maps...not sure what the exact fix would be. At this point, last change made was 6 years, so we might be looking at a complete re-write.

I will not be attending the Esri UC in San Diego next week, unfortunately.

**Comment by BrianBunker** [comment]
I've looked into this a bit more. Looks like Esri is requiring a token and payment for basemaps. I will not be providing the token, but have updated the code. This can run locally without a token, so feel free to clone the repo to get the page working locally.

**Comment by hhkaos** [comment]
> Looks like Esri is requiring a token and payment for basemaps

You are right, API keys are required now. The free developer account include 2M tiles per month and adding a credit card is optional but I totally understand you don't feel confortable adding it.

Again, thank you for this tool! I has been helpful many times to me!

**Comment by BrianBunker** [comment]
@hhkaos I've found a [work around for now](https://brianbunker.github.io/geometry-inspector/source/). Please continue to enjoy working with geometry-inspector directly in Github.
