### ISSUE TITLE
Geometry Inspector down?

### ISSUE THREAD

**Issue by kthompson** [BrianBunker/geometry-inspector#6]
Hello I have used your application here for a couple years that was previously at http://brianbunker.github.io/geometry-inspector/ but I can no longer access it. Has the url been updated?

Very handy tool btw 😄

**Comment by BrianBunker** [comment]
Hi Kevin, I'm glad you've found geometry-inspector useful too! I know I use it fairly regularly, but recently Esri changed how to access basemaps. The code for this application was very old also. I've refreshed the code and found a work-around for the Esri basemap issue (for now). You can access the [newly updated geometry-inspector hosted on Github here](https://github.com/BrianBunker/geometry-inspector/issues/4).
